/* Client Code 
let sse = new EventSource("http://localhost:8080/stream");
sse.onmessage = console.log
*/

/*
we could define the idea behind SSE as follows:

A web app “subscribes” to a stream of updates generated by a server and, whenever a new event occurs, a notification is sent to the client.

- The content type of the response header should be text/event-stream .
- The response should contain a data field followed by the message you’d like to send and should always be terminated by a double carriage return such as follows:
data: example message\n\n

*/

const app = require("express")();

app.get("/", (req, res) => res.send("hello!"));

app.get("/stream", (req, res) => {
  res.setHeader("Content-Type", "text/event-stream");
  send(res);
});

const port = process.env.PORT || 8888;

function send(res) {
  let i = 0;

  setInterval(() => {
    res.write("data: " + `hello from server ---- [${i++}]\n\n`);
  }, 1000);
}

app.listen(port);
console.log(`Listening on ${port}`);
