version: "3"

services:
  www:
    image: php:8.1.1-apache
    # the image has mysqli installed :)
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
  db:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: lamp_demo
      MYSQL_USER: lamp_demo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
